spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pfe
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwt:
    secret: secretkey
    expirationMs: 6000000
    refreshExpirationMs: 1200000000
